apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apache
  namespace: grupo3
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: thiagocingolani/grupo3-ayso:v1
        ports:
        - containerPort: 8080  
